name: conference-ppsn-2024
channels:
  - conda-forge
dependencies:
  - git=2.44.*
  - pip=24.0.*
  - python=3.12.*
  - pip:
    - ipykernel==6.29.*
    - jinja2==3.1.*
    - Markdown==3.5.*
    - matplotlib==3.8.*
    - numpy==1.26.*
    - openpyxl==3.1.*
    - pandas==2.2.*
    - scikit-learn==1.4.*
    - scipy==1.12.*
    - seaborn==0.13.*
    - six==1.16.*